default_platform(:ios)

platform :ios do
  before_all do
    cocoapods(try_repo_update_on_error: true)
  end
  
  desc "Builds and run unit tests"
  lane :test do
    scan(scheme: "BullsEye")
  end

  desc "Builds and run UI tests"
  lane :ui_test do
    scan(scheme: "UITests")
  end
end
